### PR TITLE
refactor: refresh the code paths used by the setup-playbook

### PR DESCRIPTION
**Pull request by gmarcy**

### CODE REVIEW

**Comment by gmarcy** [comment]
hmm, could it be that impish is gone and we need to move rke to jammy ?

**Comment by gmarcy** [comment]
also, many failures with
```
"ERROR    Unable to create tap device veth0-0a000004: Device or resource busy",
```
maybe CI hypervisors is in a bad state.

**Comment by ccamacho** [comment]
this change LGTM, the only I'm seeing is this https://ci.kubeinit.org/file/kubeinit-ci/jobs/eks-libvirt-3-1-2-h-pr-594938738-2022.07.22.22.26.27-1/results/1120.html but it might be already broken from a previous refactor

**Comment by gmarcy** [comment]
> this change LGTM, the only I'm seeing is this https://ci.kubeinit.org/file/kubeinit-ci/jobs/eks-libvirt-3-1-2-h-pr-594938738-2022.07.22.22.26.27-1/results/1120.html but it might be already broken from a previous refactor

error is 
```
* reading JSON file "/root/.docker/config.json": unmarshaling JSON at "/root/.docker/config.json": invalid character '\'' looking for beginning of object key string
```
which again makes me feel like corrupted hypervisor

**Comment by gmarcy** [comment]
sigh, pushed before commit and it closed this

**Review by ccamacho — APPROVED** [review]

**Pull request merged**
